version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"

python:
  version: 3.10
  install:
    - requirements: requirements-dev.txt
    - method: pip
      path: .

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

formats:
  - pdf
  - epub
